// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shutdown.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace gRPCSample.Proto {

  /// <summary>Holder for reflection information generated from shutdown.proto</summary>
  public static partial class ShutdownReflection {

    #region Descriptor
    /// <summary>File descriptor for shutdown.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShutdownReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5zaHV0ZG93bi5wcm90bxIKZ1JQQ1NhbXBsZRobZ29vZ2xlL3Byb3RvYnVm",
            "L2VtcHR5LnByb3RvMk0KD1NodXRkb3duU2VydmljZRI6CghTaHV0ZG93bhIW",
            "Lmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0",
            "eUITqgIQZ1JQQ1NhbXBsZS5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
